import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import { Space_Mono } from 'next/font/google';
import "./globals.css";

/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/

const spaceMono = Space_Mono({ 
  subsets: ['latin'], 
  weight: '400',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={/*${geistSans.variable}*/ `${spaceMono.className} antialiased items-center justify-items-center min-h-screen p-5 sm:p-20`}
      >
        {children}

        <footer className="mt-8 pt-4 border-t w-[45%] justify-items-center">
            <p><em>go vegan (vamos venga)</em> 🌱</p>
        </footer>
      </body>
    </html>
  );
}
